// Generated by https://quicktype.io
// command palette -> ctrl+shift+p
export interface UsuariosListado {
    page:        number;
    per_page:    number;
    total:       number;
    total_pages: number;
    data:        Usuario[];
    support:     Support;
}
 
//fn+F2 -> cambio mpultiplo del nombre de una varibale, constante, interface, etc
export interface Usuario {
    id:         number;
    email:      string;
    first_name: string;
    last_name:  string;
    avatar:     string;
}

export interface Support {
    url:  string;
    text: string;
}
